---
title: "Travel Arima Analysis"
author: "Byron Smith. 300504707"
date: "21/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(dplyr)
library(timetk)
library(tidyr)
covid <- read.csv("covid_19_data_portal.csv", header=TRUE, stringsAsFactors=FALSE)

# Get the travel category data
travel <- filter(covid, category == "Travel")

# Check for missing data
is.null(travel)
```

```{r message=FALSE}
# Convert parameter column to date object and rename
travel$parameter <- as.Date(travel$parameter)
travel <- rename(travel, Date = parameter)

# Convert value column to numeric 
travel$value <- as.integer(travel$value)

# Remove un-needed columns
travel_select <- select(travel, indicator_name, series_name, Date, value)


# Get all arrival data
arrivals <- filter(travel_select, grepl("arrivals", indicator_name))

# Get all departure data
departures <- filter(travel_select, grepl("departures", indicator_name))

# Drop indicator name column for arrivals and departures
arrivals <- select(arrivals, -indicator_name)
departures <- select(departures, -indicator_name)

# Widen data to have a column for each series_name
arrivals_wide <- pivot_wider(arrivals, id_cols = Date, names_from = series_name, values_from = value)
departures_wide <- pivot_wider(departures, id_cols = Date, names_from = series_name, values_from = value)

# Rename columns to remove spaces
colnames(arrivals_wide) <- make.names(colnames(arrivals_wide), unique=TRUE)
colnames(departures_wide) <- make.names(colnames(departures_wide), unique=TRUE)

# Check for missing values
any(is.na(arrivals_wide))
any(is.na(departures_wide))
```
```{r}
# Ensure that columns Auckland, Christchurch, Queenstown, Wellington and Other add to Total value.
all(mutate(arrivals_wide, SUM = Auckland + Christchurch + Queenstown + Wellington + Other)$SUM == arrivals_wide$Total)
all(mutate(departures_wide, SUM = Auckland + Christchurch + Queenstown + Wellington + Other)$SUM == departures_wide$Total)
```
```{r}
# Ensure that columns New Zealand passport and Other passports add to Total
all(mutate(arrivals_wide, SUM = New.Zealand.passport + Other.passports)$SUM == arrivals_wide$Total)
all(mutate(departures_wide, SUM = New.Zealand.passport + Other.passports)$SUM == departures_wide$Total)
```

```{r}
head(arrivals_wide)
```

